-- creating data base
create DATABASE Library_System;
USE library_system;
create table Members (
			 member_id varchar(10),
             member_name varchar(250),
             member_address varchar(250),
             reg_date int
);

alter table members modify column reg_date  varchar(255);
alter table Members modify column member_id varchar(255) primary key;

create table Books (
					isbn varchar(255) primary key,
                    book_title varchar(255),
                    category varchar(255),
                    rental_price decimal(6,2),
                    `status` varchar(255),
                    author varchar(255),
                    publisher varchar(255)
);

create table 
		return_status(
						return_id varchar(20) primary key,
						issued_id varchar(20),
						return_book_name varchar(255),
						return_date	varchar(50),
						return_book_isbn varchar(50)
);

create table Branch (
						branch_id varchar(50) primary key,
                        manager_id varchar(50),
                        branch_address varchar(255),
                        contact_no int

);
alter table branch change column contact_no  contact_on varchar(50);

create table Employe (
						emp_id varchar(50) primary key,
                        emp_name varchar(100),
                        `position` varchar(100),
                        salary int,
                        branch_id varchar(50)
);

create table issue ( 
					issued_id varchar(50) primary key,
                    issued_member_id varchar(50),
                    issued_book_name varchar(100),
                    issued_date varchar(50),
                    issued_book_isbn varchar(100),
                    issued_emp_id varchar(50)
);
rename table return_status to `return`;

alter table `return` 
drop column return_book_name,
drop column return_book_isbn;

-- Books-Related Questions
-- 1. Which books are currently unavailable for rent? 

select * from books
where `status` = "No";

-- 2. What is the most expensive book to rent in each category?


select category , max(rental_price) as MAx_price
from books
group by category ;

-- 3. How many books are there in the "Classic" category?  
select count(*)
from books
where category = "Classic";

-- 4. Which books have been issued the most?  

select issued_book_name as book_name, count(*) as Books_count
from issue 
group by book_name
order by Books_count desc;

-- 5. List all books published by "Penguin Books".

select book_title,
		row_number() over(order by Book_title) as `serial`
from books 
where publisher = "Penguin Books";

--  6. Which books have been issued more than once but never returned? 


with book_count as (
				   select * ,
                   count(*) over(partition by issued_book_name) as book_issued
                   from issue 
)
select issued_book_name as book , issued_id
from book_count as a
left join `return` as b using(issued_id)
where  book_issued > 1 and return_id is null;

-- 7. Which books are currently overdue ?  

select distinct row_number() over() as `serial`,
				issued_book_name as books
				
from issue
left join `return` using(issued_id)
where return_id is null;

-- 8. Which books have never been issued?  

select book_title
from books
left join issue on isbn = issued_book_isbn
where issued_book_isbn is null;

-- 9. What is the total revenue generated by each branch?  

with revenue_table as (
				select isbn,book_title,rental_price,
						count(issued_book_isbn) as rent,
                        rental_price * count(issued_book_isbn) as revenue
				from books 
                left join issue on isbn = issued_book_isbn
                group by isbn,book_title
                order by rent desc
)
select branch_id, sum(revenue) as total_revenue 
from revenue_table
left join issue on isbn = issued_book_isbn
left join employe on issued_emp_id = emp_id
group by branch_id ;

-- 10. Which books were issued but not returned? 


select issued_id,issued_book_isbn, book_title
from issue
left join `return` using(issued_id)
left join books on isbn = issued_book_isbn
where return_id is null;

-- Members-Related Questions
-- 11. How many members registered in 2021?  

select count(*) AS Member_num
from members
where reg_date  like "2021%" ;

-- 12. Which member has borrowed the most books? 

select member_name , member_id , count(*) as books_borrowed
from issue
left join members on member_id =  issued_member_id 
group by  member_id 
order by books_borrowed desc;

-- 13. List all members who have not borrowed any books.

select member_name , member_id , issued_id
from members
left join issue on member_id = issued_member_id
where issued_id is null;


-- 14. Which member has the most overdue books (not returned)? 


with main as (
	select issued_member_id , count(*) as overdue
    from issue
    left join `return` using(issued_id)
	where return_id  is null 
    group by issued_member_id
    order by overdue desc)
select main.*, members.member_name from main
left join members on issued_member_id = member_id; 

-- 15. What is the average number of books borrowed per member? 


select round(avg(book_count),2) as Avg_Book 
from 
(select count(*) as book_count , 
		issued_member_id
        from issue
        group by issued_member_id) as count_table;
		
-- 16. Which members have borrowed books from multiple branches? 

select issued_member_id ,count(distinct branch_id) as Total_branch
from issue 
left join employe on issued_emp_id = emp_id
group by issued_member_id
having  Total_branch > 1;

-- 17. Which members have borrowed books from the "Classic" category? 
select member_id,member_name ,
		group_concat( book_title separator ", ") as books_names
from  books
left join issue on book_title = issued_book_name
left join members on member_id = issued_member_id
where category = "Classic"
group by member_name ,member_id;

-- 18. What is the total number of unique members who have borrowed books? 

select 
	count(distinct issued_member_id) as total_unique_members
from issue;

-- 19. Which members have borrowed books from the most branches? 

select issued_member_id,member_name, count(distinct branch_id) as borrowed_branch
from issue
left join members on issued_member_id = member_id
left join employe on issued_emp_id = emp_id 
group by issued_member_id,member_name
having borrowed_branch > 2 ;

-- 20. List all members who have borrowed books from more than one branch.  

select issued_member_id,member_name, count(distinct branch_id) as borrowed_branch
from issue
left join members on issued_member_id = member_id
left join employe on issued_emp_id = emp_id 
group by issued_member_id,member_name
having borrowed_branch > 1 ;


-- Employees-Related Questions
-- 21. Which employee has issued the most books?  

select emp_id,emp_name,count(issued_emp_id) as issued_num
from issue
left join employe on issued_emp_id = emp_id
group by emp_id,emp_name
order by issued_num desc;

-- 22. What is the total salary expenditure for each branch?  

select branch_id, sum(salary) as salary_expenditure 
from employe 
group by branch_id 
order by branch_id;

-- 23. List all employees who are managers.

select row_number() over(order by emp_name) as `serial` , emp_name 
from employe
where position = 'manager';

-- 24. Which branch has the highest number of employees?  

select branch_id , count(*) as employe_num 
from employe
group by branch_id
order by employe_num desc;

-- 25. What is the average salary of employees by position?  

select `position` ,avg_salary
from (  select `position`,
				round(avg(salary),2) as avg_salary 
		from employe
		group by `position`) as avg_table;
			
 -- 26. Which employee has the highest salary, and what is their branch? 
 select  *
 from employe
 where salary = max(salary);
 
-- 27. Which employee has the highest number of books issued in a single month? 

select emp_id , emp_name  , 
	   count(issue.issued_date) as count_books ,
       date_format(issued_date,'%Y %M') as date_Month
from  employe
left join issue on  emp_id  = issued_emp_id
group by emp_id , emp_name,date_Month
order by emp_id;

-- 28. What is the total number of books issued by each manager?

select emp_name , count(issued_id) as books_issue
from issue
left join employe on issued_emp_id = emp_id
where `position` = "manager"
group by emp_name
order by books_issue desc;

-- 29. List all employees who have issued books in 2024.  
select distinct emp_name 
from issue
left join employe on emp_id = issued_emp_id
where year(issued_date) = "2024";

-- 30. Which employees have issued books from the "Fantasy" category?

select distinct emp_name 
from issue
left join books on issued_book_isbn = isbn
left join employe  on emp_id = issued_emp_id
where category = "Fantasy";

-- Branch-Related Questions
-- 31. How many branches are managed by each manager? 

select emp_name , count(manager_id ) as branch_count, 
	   group_concat(b.branch_id) as branch_ids
from employe e
join branch b on manager_id = emp_id
group by emp_name;

-- 32. Which branch has issued the most books? 

select branch_id , count(issued_id) as 'books issu'
from issue
left join employe on issued_emp_id = emp_id
group by branch_id;

-- 33. List all branches and their contact numbers.  

select branch_id , contact_on
from branch;

-- 34. What is the total number of books issued by employees in each branch? 

select  branch_id , 
		group_concat(distinct issued_emp_id) as "emp id's" , 
		count(issued_id) as books_issue
from issue
join employe on issued_emp_id = emp_id
group by branch_id;

-- 35. Which branch has the highest total rental income?  

with BOOKS_RENTAL AS (
	 select issued_book_isbn,issued_book_name, 
     rental_price, count(issued_id) as books_rent,
     rental_price * count(issued_id) as total_rent
     from issue
	 left join books on isbn = issued_book_isbn
     group by issued_book_isbn,issued_book_name
)

select branch_id , sum(total_rent) as "Branch total rent"
from books_rental 
left join issue using(issued_book_isbn)
left join employe on issued_emp_id = emp_id
group by branch_id;

-- General Analytical Questions
-- 36. What is the total rental income generated from all issued books?
with count_table as
( select isbn , rental_price , count(issued_id) as book_count 
from issue
left join books on isbn = issued_book_isbn
group by isbn 
)

select sum( rental_price * book_count) as "Total Rental Income"
from count_table ;

-- 37. Which book category generates the highest rental income?  

with count_table as
( select isbn , rental_price , count(issued_id) as book_count 
from issue
left join books on isbn = issued_book_isbn
group by isbn 
)

select category,sum( c.rental_price * book_count) as Total_Rental_Income
from count_table c
left join books b using(isbn)
group by category
order by Total_Rental_Income desc;

-- 38. How many books were issued in each month of 2024? 

select monthname(issued_date) as per_month , count(*) as books_issue
from issue
where year(issued_date) = 2024
group by per_month;

-- 39. Which category of books is the most popular (most issued)?  
select category , count(issued_id) as issued
from issue 
left join books on issued_book_isbn = isbn
group by category
order by issued desc
limit 1;

-- 40. What is the total number of books returned in 2023?  

select date_format(return_date,'%Y %M') as date_return , count(*) as book_return
from `return` 
where year(return_date) = 2023
group by date_return;

-- 41. What is the average time (in days) between book issuance and return?

with day_count as 
( select issued_id ,datediff(return_date,issued_date) as day_gap
from `return`
join issue using(issued_id)
)

select round(avg(day_gap),2) as 'Avarage Day Gap' from day_count;

-- 42. What is the total number of books issued by each employee? 

select issued_emp_id, emp_name , count(issued_id) as Books_issued
from issue
left join employe on issued_emp_id = emp_id
group by issued_emp_id, emp_name;

-- 43. What is the total number of books issued by each branch? 

select branch_id, count(issued_id) as Books_issued
from issue
left join employe on issued_emp_id = emp_id
group by branch_id;

-- 44. What is the total number of books issued in 2024? 

select sum(books_issued) as "books issued in 2024"
from (
select year(issued_date) , count(*) books_issued
from issue
where year(issued_date) = 2024
group by issued_date) as table_1;

-- 45. What is the total number of books returned in 2024? 

select count(*) as "books returned in 2024"
from `return`
where year(return_date) = 2024;

 -- Advanced Questions
-- 46. Which books have been issued more than once but never returned? 

with main as
(select issued_book_isbn , book_title 
from issue
left join books on issued_book_isbn = isbn
group by issued_book_isbn , book_title 
having  count(issued_id) > 1)

select book_title 
from main
left join issue on issued_book_name = book_title 
left join `return` using(issued_id)
where return_id is null ;

-- 47. What is the total revenue generated by each branch?

select branch_id , sum(books_count * rental_price) as "revenue generated"
from
(select count(issued_id) as books_count , rental_price,issued_book_isbn
from issue
left join books on isbn = issued_book_isbn
group by issued_book_isbn,rental_price) as main
left join issue using(issued_book_isbn)
left join employe on emp_id = issued_emp_id
group by branch_id ;

-- 48. Which members have borrowed books from multiple branches?  

select issued_member_id , count(branch_id) as branch_count
from issue 
left join employe on issued_emp_id = emp_id
group by issued_member_id
having count(branch_id) > 1;

-- 49. What is the average time (in days) between book issuance and return?  

select round(avg(date_defferent)) as "avg time of book return"
from
(select datediff(return_date,issued_date) as date_defferent
from issue
join `return` using(issued_id)) as avg_table;

-- 50. Which position employe issued more books ? 

select `position` , count(issued_id) as books_count
from issue
join employe on issued_emp_id = emp_id
group by `position`
order by books_count desc;

